import argparse
import time

from importlib import metadata


__version__ = metadata.version("poppy")


def command_summary(args):
    print("Command poppy::summary starts.")
    start = time.time()
    from poppy.summary_main import summary_main
    summary_main(args.mode, args.indir, args.outfile, args.suffix)
    print("Command poppy::summary ends. Time elapsed: {:,} sec.".format(int(time.time() - start)))


def command_ris(args):
    print("Command poppy::remove_invariant_sites starts.")
    start = time.time()
    from poppy.remove_invariant_sites import main
    print("\tRemoving invariant sites...")
    main(args.input, args.output, args.format)
    print("Command poppy::remove_invariant_sites ends. Time elapsed: {:,} sec.".format(int(time.time() - start)))


def command_subseq(args):
    from poppy.subseq import main
    main(args)


def command_plink2treemix(args):
    from poppy.plink2treemix import main
    main(args.input, args.output)


def main():

    # global arguments
    parser = argparse.ArgumentParser(
        description = "Miscellaneous python scripts for population genomics.",
        usage = "poppy <commands> [-h/--help] [Options]"
    )
    parser.add_argument("-V", "--version", action = "version", version = __version__,
                        help = "Show the version number")
    subparsers = parser.add_subparsers(title = "Commands", metavar = "")

    # summary
    help_txt = "Scan directory to summarize stat files."
    help_txt += " See `poppy summary -h`."
    parser_summary = subparsers.add_parser("summary", help = help_txt)
    parser_summary.add_argument("-m", "--mode", choices = ["flag", "bam", "vcf"],
                                help = "Output filetype to summarize.")
    parser_summary.add_argument("-i", "--indir",
                                help = "PATH to directory that contains stat files.")
    parser_summary.add_argument("-o", "--outfile",
                                help = "PATH to output file.")
    parser_summary.add_argument("--suffix",
                                help = "Suffix of files to summary. (e.g. vcf.stat, cov, etc.)")
    parser_summary.set_defaults(handler = command_summary)

    # remove-invariant-sites
    help_txt = "Remove invariant sites an alignment file."
    help_txt += " See `poppy remove-invariant-sites -h`."
    parser_alnkit = subparsers.add_parser("remove-invariant-sites", help = help_txt)
    parser_alnkit.add_argument("-i", "--input",
                               help = "PATH to input alignment file. PHYLIP from vcf2phylip is assumed.")
    parser_alnkit.add_argument("-o", "--output",
                               help = "PATH to output alignment file.")
    parser_alnkit.add_argument("--format", choices = ["fasta", "phylip"],
                               help = "Format of output alignment.")
    parser_alnkit.set_defaults(handler = command_ris)

    # subseq
    help_txt = "Extract partial sequence from FASTA file."
    help_txt += " See `poppy subseq -h`."
    parser_faskit = subparsers.add_parser("subseq", help = help_txt)
    parser_faskit.add_argument("-f", "--fasta",
                               help  = "PATH to FASTA file of genome sequence.")
    parser_faskit.add_argument("-c", "--chrom",
                               help = "Chromosome or contig name.")
    parser_faskit.add_argument("-p", "--pos", type = int,
                               help = "Position of variant.")
    parser_faskit.add_argument("-r", "--range", type = int,
                               help = "Range of sequences too show around variant.")
    parser_faskit.add_argument("--ref", help = "Reference nucleotide.")
    parser_faskit.add_argument("--alt", help = "Alternative variant.")
    parser_faskit.set_defaults(handler = command_subseq)

    # plink2treemix
    help_txt = "Convert plink freq file to treemix input format."
    help_txt += " See `poppy plink2treemix -h`."
    parser_plink2treemix = subparsers.add_parser("plink2treemix", help = help_txt)
    parser_plink2treemix.add_argument("-i", "--input",
                                      help = "PATH to input file generated by `plink --freq`.")
    parser_plink2treemix.add_argument("-o", "--output",
                                      help = "PATH to output file.")
    parser_plink2treemix.set_defaults(handler = command_plink2treemix)

    args = parser.parse_args()
    if hasattr(args, "handler"):
        args.handler(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
